FROM node:8

COPY package.json /package.json

RUN npm install

Run npm install --save yarn-install

FROM python:3.6.0

COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt


WORKDIR /home/Algocynfas/
